## 1
name: Test and deploy

## Actions that will be executed when you push code currently none
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

## 2
jobs:
  ## 3
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Run Kotlin Linter
        run: ./gradlew ktlintStagingDebugCheck

      - name: Unit tests
        run: ./gradlew test

  ## 4
  android_tests:
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest
  
  ## 5
  build:
    runs-on: ubuntu-latest
    steps:
      # 5.1
      - name: Checkout code
        uses: actions/checkout@v2
      # 5.2
      - name: Generate Debug APK
        run: ./gradlew assembleDebug
      # 5.3
      - name: Sign APK
        with:
          releaseDirectory: app/build/outputs/apk/debug
      # 5.4
      - uses: actions/upload-artifact@master
        with:
          name: debug.apk
