name: CI

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@main
    - name: Build debug apk
      run: ./gradlew clean assembleDebug
    - name: Create release and upload apk
      uses: firdausmaulan/ExoPlayer-Playground@main
      with:
        tag_name: v1.0.0
        asset_path: app/build/outputs/apk/debug/app-debug.apk
        asset_name: debugApp.apk
        asset_content_type: application/zip
